title: Phillip Peng # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="/pdf/resume_phillip_2024.pdf">Resume</a> 
  <br><br> 
  <a href="https://www.linkedin.com/in/phillippeng/">LinkedIn Profile</a> 
  <br>
  ### About Me

  Accomplished Data Strategist and Machine Learning Engineer with a robust track record in spearheading AI/ML innovations and deploying machine learning models in high-stakes production environments. With a specialty in crafting complex data pipelines, model fine-tuning, and performance optimization, I bring forth a blend of technical acumen and strategic insight. I excel at rallying cross-functional teams to harness the power of data-driven solutions, driving significant business impact. My academic background in Agricultural Economics, complemented by ongoing development in AI, Machine Learning, and Project Management, equips me with a unique perspective and versatile skill set in the tech landscape.
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
