title: Phillip Peng # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="/pdf/resume_phillip_2024.pdf">Resume</a> 
  <br><br> 
  <a href="https://www.linkedin.com/in/phillippeng/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
